In [9]:
import numpy as np

**Задание**

Нужно создать массив из 100 элементов 1 (от 1 до 100), переформатировать в формат (10 * 10), Сделать из слайсинг С шагом 2 по каждой оси.


In [ ]:
a = np.arange(1, 101).reshape(10 , 10)[::2, ::2]
a

array([[ 1,  3,  5,  7,  9],
       [21, 23, 25, 27, 29],
       [41, 43, 45, 47, 49],
       [61, 63, 65, 67, 69],
       [81, 83, 85, 87, 89]])

**Задание**

Нужно написать функцию которая по заданной длине последовательности находит среднее арифметическое Её членов.
Реализуйте задачу с помощью библиотеки Numpy и без помощи Numpy, Сравните время выполнения.
Важно, что в одном случае должны использоваться только структуры Стандартной поставки языка Python 3, А в случае с Numpy работать лучше только с его абстракциями(Начиная создание массивов и заканчивая вычислениЕм метрики).

In [12]:
def mean_list(array):
    return sum(array) / len(array)
#mean_list([2, 3, 4, 5, 6])

In [14]:
#wo numpy
%%time
a = list(range(10000000))
mean_list(a)

CPU times: user 201 ms, sys: 216 ms, total: 417 ms
Wall time: 415 ms


In [10]:
#w numpy
%%time
a_numpy = np.arange(1, 10000001)
a_numpy.mean()


CPU times: user 24 ms, sys: 21.8 ms, total: 45.8 ms
Wall time: 49.9 ms


**Задание**

Пусть мы имеем два массива(Заданы ниже в коде). Требуется создать массив который получает результат поэлементно True если чётные элементы 1 массива больше 2 True если нечётные элементы 2 больше алиментов 1. В противном случае возвращать false.
Реализовать задачи с помощью Нампи
Пример массива и результата:
a = [7, 3, 5, 9, 2, 5, 4, 8, 9, 0]
b = [2, 8, 6,  , 1, 3, 2, 9, 5, 1]
res = [False, False, True, True, False, True, False, False, False, False]

In [17]:
a = np.array([7, 3, 5, 9, 2, 5, 4, 8, 9, 0])
b = np.array([2, 8, 6, 7, 1, 3, 2, 9, 5, 1])
res = np.array([False, False, True, True, False, True, False, False, False, False])

my_res = a > b
my_res[::2] = a[::2] < b[::2]
my_res


array([False, False,  True,  True, False,  True, False, False, False,
       False])

In [22]:
myres2 = np.where(
 np.arange(1, len(a) + 1) % 2 == 0, 
 a > b,
 b > a
)
myres2

array([False, False,  True,  True, False,  True, False, False, False,
       False])

**Задание**

Создайте массив размера 10 со значениями от 0 до 1(С равномерным значением интервала), не включая концы.

In [27]:
b = np.linspace(0, 1, 12)[1:-1]
b

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

**Задание**

Создайте случайный вектор размера 10 и отсортируйте его.

In [29]:
np.sort(np.random.rand(10))

array([0.0016249 , 0.0502046 , 0.16154475, 0.23155386, 0.69906443,
       0.86465398, 0.96736908, 0.97234177, 0.98383686, 0.99943618])

**Задание**

Замените максимальные значения на 0

In [31]:
c = np.random.rand(10)
c
c[c == np.max(c)] = 0
c

array([0.54390043, 0.3411653 , 0.94938254, 0.2160844 , 0.62155355,
       0.78142596, 0.51115578, 0.00419936, 0.        , 0.22322075])

**Задание**

Нужно вычесть из каждой строки матрицы их среднее

In [32]:
x = np.random.rand(5, 10)
print(x)
x- x.mean(axis=1, keepdims=True)

[[0.89664317 0.07336473 0.31255899 0.27444782 0.96844778 0.05988343
  0.67569207 0.99509344 0.06182958 0.15544375]
 [0.00600261 0.67654937 0.82723229 0.7889467  0.19402624 0.52876086
  0.67530948 0.31525798 0.24505366 0.34086607]
 [0.70437435 0.35160301 0.19771044 0.37188227 0.53672502 0.60296731
  0.5872498  0.787735   0.95912989 0.51990414]
 [0.17807182 0.28266868 0.69072329 0.16318361 0.7839585  0.20040605
  0.52530808 0.79898724 0.16229641 0.25010113]
 [0.89257209 0.65046021 0.49381746 0.19967758 0.17724456 0.03302601
  0.03710433 0.69783389 0.41924707 0.22993037]]


array([[ 0.44930269, -0.37397574, -0.13478148, -0.17289266,  0.52110731,
        -0.38745705,  0.22835159,  0.54775296, -0.38551089, -0.29189672],
       [-0.45379791,  0.21674884,  0.36743176,  0.32914618, -0.26577429,
         0.06896034,  0.21550896, -0.14454255, -0.21474687, -0.11893446],
       [ 0.14244623, -0.21032511, -0.36421769, -0.19004585, -0.0252031 ,
         0.04103918,  0.02532168,  0.22580688,  0.39720177, -0.04202398],
       [-0.22549866, -0.1209018 ,  0.28715281, -0.24038687,  0.38038802,
        -0.20316443,  0.1217376 ,  0.39541676, -0.24127407, -0.15346935],
       [ 0.50948073,  0.26736886,  0.1107261 , -0.18341377, -0.20584679,
        -0.35006535, -0.34598703,  0.31474253,  0.03615571, -0.15316098]])

**Задание**  

Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [ ]:
a = np.array([[1, 2, 3, 3, 1],
             [6, 8, 11, 10, 7]]).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [ ]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

**Задание** 

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [ ]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

**Задание**  
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [ ]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1]) / (a_centered.shape[0] - 1)
a_centered_sp

2.0

In [ ]:
a_centered[:, 0].dot(a_centered[:, 1]), a_centered[:, 0] @ a_centered[:, 1]

(8.0, 8.0)

**Задание**   
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.


В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [ ]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

### Тема “Работа с данными в Pandas”

**Задание 1**  
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные: 
[1, 1, 1, 2, 2, 3, 3], 
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [ ]:
import pandas as pd

In [ ]:
authors = pd.DataFrame({'author_id':[1, 2, 3],
                      'author_name':['Тургенев', 'Чехов', 'Островский']})
books = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                   'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                   'price':[450, 300, 350, 500, 450, 370, 290]})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

**Задание 2**  
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.


In [ ]:
authors_price = pd.merge(authors, books, on='author_id')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

**Задание 3**  
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


In [ ]:
top5 = authors_price.sort_values('price', ascending=False).head(5)
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [ ]:
authors_price.nlargest(5, 'price')

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [ ]:
authors_price.sort_values(by=['price'], ascending=False).head(5).reset_index(drop=True)

author_id author_name         book_title  price
0          2       Чехов   Толстый и тонкий    500
1          1    Тургенев        Отцы и дети    450
2          2       Чехов    Дама с собачкой    450
3          3  Островский              Гроза    370
4          1    Тургенев  Дворянское гнездо    350

**Задание 4 (*)**  
Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора,минимальная, максимальная и средняя цена на книги этого автора.


In [ ]:
# 1 вариант
authors_stat = authors_price.groupby('author_name')['price'].agg(['min', 'max', 'mean'])
authors_stat.rename(columns={'max': 'max_price', 
                             'mean': 'mean_price', 
                             'min': 'min_price'}, 
                    inplace=True)
#authors_stat.reset_index(level='author_name', inplace=True)
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

In [ ]:
# 2 вариант
authors_stat = authors_price.groupby('author_name').agg(
    min_price=pd.NamedAgg(column='price', aggfunc='min'),
    max_price=pd.NamedAgg(column='price', aggfunc='max'),
    mean_price=pd.NamedAgg(column='price', aggfunc='mean'))
authors_stat.reset_index(level='author_name', inplace=True)
authors_stat

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000

In [ ]:
# 3 вариант
authors_stat = authors_price.groupby('author_name').agg(
    min_price=('price', 'min'),
    max_price=('price', 'max'),
    mean_price=('price', 'mean'))
authors_stat.reset_index(level='author_name', inplace=True)
authors_stat

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000

In [ ]:
# 4 вариант
authors_stat = authors_price.groupby('author_name')['price'].agg(
    min_price='min',
    max_price='max',
    mean_price='mean')
authors_stat.reset_index(level='author_name', inplace=True)
authors_stat

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000

In [ ]:
# 5 вариант
autor_name = authors_price['author_name'].unique()
min_price = authors_price.groupby('author_id')['price'].min()
mean_price = authors_price.groupby('author_id')['price'].mean()
max_price = authors_price.groupby('author_id')['price'].max()

authors_stat = pd.DataFrame({'author_name' : autor_name,
                              'min_price' : min_price,
                              'mean_price' : mean_price,
                              'max_price' : max_price})
authors_stat.reset_index(drop=True, inplace=True)
authors_stat

author_name  min_price  mean_price  max_price
0    Тургенев        300  366.666667        450
1       Чехов        450  475.000000        500
2  Островский        290  330.000000        370

In [ ]:
# 6 вариант
authors_stat = pd.pivot_table(data=authors_price, 
                              index=['author_name'], 
                              values=['price'],
                              aggfunc={'price':[min, max, np.mean]}).rename(
    columns={"max":"max_price",
             "min":"min_price",
             "mean":"mean_price"})

authors_stat.columns = authors_stat.columns.droplevel(0)         
authors_stat = authors_stat.reset_index(level='author_name') 
authors_stat

author_name  max_price  mean_price  min_price
0  Островский      370.0  330.000000      290.0
1    Тургенев      450.0  366.666667      300.0
2       Чехов      500.0  475.000000      450.0

**Задание 5 (*)**  
Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.


In [ ]:
authors_price['cover'] =  ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [ ]:
book_info = pd.pivot_table(authors_price, 
                           values='price', 
                           index='author_name', 
                           columns='cover', 
                           aggfunc='sum')
#book_info.columns.name = None 
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      NaN
Тургенев      650.0    450.0
Чехов           NaN    950.0

In [ ]:
book_info.fillna(0, inplace=True)

In [ ]:
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [ ]:
import pickle

with open('book_info.pkl', 'wb') as handle:
    pickle.dump(book_info, handle, protocol=pickle.HIGHEST_PROTOCOL)

with open('book_info.pkl', 'rb') as handle:
    book_info2 = pickle.load(handle)

book_info2

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [ ]:
# 2 вариант
book_info.to_pickle('book_info.pkl')
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0